export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_ABSENCE_START = "GET_ABSENCE_START";
export const GET_ABSENCE_SUCCESS = "GET_ABSENCE_SUCCESS";
export const GET_ABSENCE_FAIL = "GET_ABSENCE_FAIL";

export const DELETE_ABSENCE_START = "DELETE_ABSENCE_START";
export const DELETE_ABSENCE_SUCCESS = "DELETE_ABSENCE_SUCCESS";
export const DELETE_ABSENCE_FAIL = "DELETE_ABSENCE_FAIL";

export const CREATE_ABSENCE_START = "CREATE_ABSENCE_START";
export const CREATE_ABSENCE_SUCCESS = "CREATE_ABSENCE_SUCCESS";
export const CREATE_ABSENCE_FAIL = "CREATE_ABSENCE_FAIL";

export const GET_STUDENT_LIST_START = "GET_STUDENT_LIST_START";
export const GET_STUDENT_LIST_SUCCESS = "GET_STUDENT_LIST_SUCCESS";
export const GET_STUDENT_LIST_FAIL = "GET_STUDENT_LIST_FAIL";

export const GET_ASSIGNMENT_LIST_START = "GET_ASSIGNMENT_LIST_START";
export const GET_ASSIGNMENT_LIST_SUCCESS = "GET_ASSIGNMENT_LIST_SUCCESS";
export const GET_ASSIGNMENT_LIST_FAIL = "GET_ASSIGNMENT_LIST_FAIL";

export const GET_GRADED_ASSIGNMENT_LIST_START = "GET_GRADED_ASSIGNMENT_LIST_START";
export const GET_GRADED_ASSIGNMENT_LIST_SUCCESS = "GET_GRADED_ASSIGNMENT_LIST_SUCCESS";
export const GET_GRADED_ASSIGNMENT_LIST_FAIL = "GET_GRADED_ASSIGNMENT_LIST_FAIL";

export const CREATE_GRADED_ASSIGNMENT_START = "CREATE_GRADED_ASSIGNMENT_START";
export const CREATE_GRADED_ASSIGNMENT_SUCCESS = "CREATE_GRADED_ASSIGNMENT_SUCCESS";
export const CREATE_GRADED_ASSIGNMENT_FAIL = "CREATE_GRADED_ASSIGNMENT_FAIL";

export const GET_STUDENT_DETAIL_START = "GET_STUDENT_DETAIL_START";
export const GET_STUDENT_DETAIL_SUCCESS = "GET_STUDENT_DETAIL_SUCCESS";
export const GET_STUDENT_DETAIL_FAIL = "GET_STUDENT_DETAIL_FAIL";

export const GET_TEACHER_DETAIL_START = "GET_TEACHER_DETAIL_START";
export const GET_TEACHER_DETAIL_SUCCESS = "GET_TEACHER_DETAIL_SUCCESS";
export const GET_TEACHER_DETAIL_FAIL = "GET_TEACHER_DETAIL_FAIL";

export const CREATE_ASSIGNMENT_START = "CREATE_ASSIGNMENT_START";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";

export const GET_ASSIGNMENT_DETAIL_START = "GET_ASSIGNMENT_DETAIL_START";
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";

export const DELETE_ASSIGNMENT_START = "DELETE_ASSIGNMENT_START";
export const DELETE_ASSIGNMENT_SUCCESS = "DELETE_ASSIGNMENT_SUCCESS";
export const DELETE_ASSIGNMENT_FAIL = "DELETE_ASSIGNMENT_FAIL";

export const UPDATE_ASSIGNMENT_START = "UPDATE_ASSIGNMENT_START";
export const UPDATE_ASSIGNMENT_SUCCESS = "UPDATE_ASSIGNMENT_SUCCESS";
export const UPDATE_ASSIGNMENT_FAIL = "UPDATE_ASSIGNMENT_FAIL";

export const UPDATE_AVATAR_START = "UPDATE_AVATAR_START";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_FAIL = "UPDATE_AVATAR_FAIL";

export const GET_AVATAR_START = "GET_AVATAR_START";
export const GET_AVATAR_SUCCESS = "GET_AVATAR_SUCCESS";
export const GET_AVATAR_FAIL = "GET_AVATAR_FAIL";