# Generated by Django 3.1.7 on 2021-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210223_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='fdsfsdfdsfsdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ic_number',
            field=models.CharField(default='fdsfsdfdsf', max_length=100),
            preserve_default=False,
        ),
    ]
