# Generated by Django 3.1.7 on 2021-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210306_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_and_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_handled',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_parttime',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Terminated'), (3, 'Suspended')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
