# Generated by Django 3.1.7 on 2021-03-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210316_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user',
            new_name='student',
        ),
    ]
