# Generated by Django 3.1.7 on 2021-03-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210322_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('student', 'date')},
        ),
    ]
